# Generated by Django 5.2.14 on 2026-05-14 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wage_rate', models.DecimalField(decimal_places=2, help_text='Snapshot of daily wage when attendance was recorded.', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='companies.company')),
            ],
            options={
                'db_table': 'attendance_attendance',
                'ordering': ['-date', 'labour__name'],
            },
        ),
    ]
