# Generated by Django 5.2.14 on 2026-05-14 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('companies', '0001_initial'),
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='partial', max_length=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Outstanding wage balance immediately after this payment.', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='attendance.attendance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_payments', to='companies.company')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='labour.labour')),
            ],
            options={
                'db_table': 'labour_payments_labourpayment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
