# Generated by Django 5.2.14 on 2026-05-15 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='companies.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='sites.site')),
            ],
            options={
                'db_table': 'materials_material',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField()),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14)),
                ('calculated_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: quantity_used × rate_per_unit at time of entry', max_digits=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='materials.material')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usage', to='sites.site')),
            ],
            options={
                'db_table': 'materials_usage',
                'ordering': ['-usage_date', '-created_at'],
            },
        ),
    ]
