# Generated by Django 5.2.14 on 2026-05-14 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='companies.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='sites.site')),
            ],
            options={
                'db_table': 'labour_labour',
                'ordering': ['name'],
            },
        ),
    ]
