# Generated by Django 6.0.7 on 2026-07-13 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Admin login'), ('disable_user', 'Disable user'), ('enable_user', 'Enable user'), ('update_user', 'Update user'), ('delete_user', 'Delete user'), ('renew_subscription', 'Renew subscription'), ('disable_subscription', 'Disable subscription'), ('update_subscription', 'Update subscription'), ('support_reply', 'Support reply'), ('support_status', 'Support status change'), ('other', 'Other')], max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
